### ISSUE TITLE
Crashes after examinations

### ISSUE THREAD

**Issue by limur903** [trigger-death/SunriderAcademyPureVN#15]
In PureVN mode, the game crashes after all examinations. I tried from a "skip the common route" start on the Asaga route, and I also tried from just a normal start. I have the 18+ mod installed. 
[traceback.txt](https://github.com/trigger-death/SunriderAcademyPureVN/files/3046532/traceback.txt)

**Comment by limur903** [comment]
The issue didn't seem to happen with the Choice mode on, but I ran into a dead-end with that when skipping the common route. Got the disappointed sister ending after choosing the Asaga route.

**Comment by trigger-segfault** [comment]
I'm pushing the fix to releases right now. Sorry about that. I swear I checked the notifications earlier today.
